```
Q1. Executive Summary: Total revenue, total customers,
    total orders, ARPU, repeat purchase rate. Single row.

Q2. Revenue by state with growth: State, revenue,
    pct_of_total, rank by revenue.

Q3. Top 5 products by profit margin with their
    category ranking.

Q4. Customer cohort analysis: Cohort month,
    cohort size, revenue in months 0, 1, 2 after acquisition.

Q5. Churn risk report: All customers with
    churn_risk = 'High'. Show days inactive,
    last order, total lifetime value.

Q6. Market basket: Top 10 product pairs
    bought together. Show pair and frequency.
```


--Q1 shows total revenue per customer 
-- shows repeat purchase rate of customers
WITH customer_orders AS(
	SELECT 
		customer_id,
		COUNT(DISTINCT order_id) AS order_count
	FROM fact_orders fo 
	GROUP BY customer_id
),
summary AS(
	SELECT 
		ROUND(SUM(unit_price * quantity * (1 - discount_pct / 100)),2
		) AS total_revenue,
		COUNT(DISTINCT fo.customer_id) AS total_customers,
		COUNT(DISTINCT fo.order_id) AS total_orders
	FROM fact_orders fo 
	JOIN fact_order_items fi ON fo.order_id = fi.order_id
)
SELECT 
	s.total_revenue,
	s.total_customers,
	s.total_orders,
	
	ROUND(
		s.total_revenue / NULLIF(s.total_customers,0),2
		) AS arpu,
	-- Move repeat_purchase_rate into the summary CTE directly:
    ROUND(
        COUNT(DISTINCT CASE WHEN order_count > 1
            THEN fo.customer_id END) * 100.0
        / NULLIF(COUNT(DISTINCT fo.customer_id), 0), 2
    ) AS repeat_purchase_rate
FROM summary s 
CROSS JOIN customer_orders co 
GROUP BY s.total_revenue,
	s.total_customers,
	s.total_orders;



--Q2 shows revenue generated by each state 
-- order by highest revennue to lowest revenue 
--shows percentage of total revenue by the state
WITH state_cal AS(
	SELECT 
		state,
		ROUND(SUM(unit_price * quantity * (1 - discount_pct / 100)),2
		) AS revenue
	FROM fact_orders fo 
	JOIN fact_order_items fi ON fo.order_id = fi.order_id
	GROUP BY state
)
SELECT state, revenue,
    ROUND(revenue * 100.0 / SUM(revenue) OVER(), 2) AS pct_of_total,
    RANK() OVER (ORDER BY revenue DESC) AS revenue_rank
FROM state_cal 
ORDER BY revenue DESC;



--Q3 shows products ranked by profit_margin_pct
--shows top 5 products 
-- shows product and revenue rank in that category
WITH product_stats AS (
    SELECT
        dp.product_id,dp.product_name,
        dp.category,
        SUM(fi.quantity) AS total_units_sold,
        SUM(fi.unit_price * fi.quantity * (1 - fi.discount_pct / 100.0)
        ) AS total_revenue,
        SUM(
            (
                fi.unit_price * fi.quantity
                * (1 - fi.discount_pct / 100.0)
            ) - (dp.cost * fi.quantity)
        ) AS total_profit
        
    FROM fact_order_items fi
    JOIN dim_products dp ON fi.product_id = dp.product_id
    GROUP BY
        dp.product_id, dp.product_name, dp.category
),
ranked_products AS (
    SELECT
        *,
        ROUND( total_profit * 100.0 / NULLIF(total_revenue, 0),
            2) AS profit_margin_pct,
        RANK() OVER (
            PARTITION BY category
            ORDER BY total_revenue DESC
        ) AS revenue_rank_in_category
    FROM product_stats
)
SELECT
    product_id,product_name,
    category,profit_margin_pct,
    revenue_rank_in_category
FROM ranked_products
ORDER BY profit_margin_pct DESC
LIMIT 5;



--Q4. Shows customer first purchase month
--shows customers each month revenue 
WITH customer_cohorts AS (
    SELECT
        customer_id,
        DATE_TRUNC('month', MIN(order_date)) AS cohort_month
    FROM fact_orders
    GROUP BY customer_id
),
customer_orders AS (
    SELECT
        fo.customer_id, cc.cohort_month,
        DATE_TRUNC('month', fo.order_date) AS order_month,

        DATE_PART('month',AGE(
                DATE_TRUNC('month', fo.order_date),
                cc.cohort_month
            )
        ) AS month_number,

        SUM(
            oi.unit_price * oi.quantity * (1 - oi.discount_pct / 100.0)
        ) AS revenue

    FROM fact_orders fo
    JOIN customer_cohorts cc ON fo.customer_id = cc.customer_id
    JOIN fact_order_items oi ON fo.order_id = oi.order_id
    GROUP BY
        fo.customer_id, cc.cohort_month, 
        DATE_TRUNC('month', fo.order_date)
)
SELECT
    cohort_month,
    COUNT(DISTINCT customer_id) AS cohort_size,
    ROUND(
        SUM(
            CASE WHEN month_number = 0 THEN revenue ELSE 0
            END
        ), 2) AS revenue_month_0,

    ROUND(
        SUM(
            CASE WHEN month_number = 1 THEN revenue ELSE 0
            END
        ), 2
    ) AS revenue_month_1,

    ROUND(
        SUM(
            CASE WHEN month_number = 2 THEN revenue ELSE 0
            END
        ), 2
    ) AS revenue_month_2
FROM customer_orders
GROUP BY cohort_month
ORDER BY cohort_month;



--Q5
-- Identify customers who are at high churn risk based on inactivity.
-- Calculate their last order date and days inactive relative to the dataset.
-- Also show their total lifetime spending for prioritizing retention efforts.
WITH customer_stats AS (
    SELECT
        fo.customer_id,
        MAX(fo.order_date) AS last_order,
        (
            SELECT MAX(order_date)
            FROM fact_orders
        ) - MAX(fo.order_date) AS days_inactive,

        ROUND(
            SUM(
                oi.unit_price
                * oi.quantity
                * (1 - oi.discount_pct / 100.0)
            ), 2
        ) AS total_lifetime_value

    FROM fact_orders fo
    JOIN fact_order_items oi ON fo.order_id = oi.order_id
    GROUP BY fo.customer_id
)
SELECT
    customer_id,
    days_inactive,
    last_order,
    total_lifetime_value
FROM customer_stats
WHERE days_inactive > 60
ORDER BY days_inactive DESC;



-- Q6 Find the product pairs most frequently purchased together.
-- Self-join order items so two different products from the same order form a pair.
-- Count distinct orders for each pair and return the top 10.
SELECT
    p1.product_name || ' + ' || p2.product_name AS pair,
    COUNT(DISTINCT oi1.order_id) AS frequency

FROM fact_order_items oi1
JOIN fact_order_items oi2 ON oi1.order_id = oi2.order_id
AND oi1.product_id < oi2.product_id

JOIN dim_products p1 ON oi1.product_id = p1.product_id
JOIN dim_products p2 ON oi2.product_id = p2.product_id

GROUP BY
    p1.product_name, p2.product_name
ORDER BY frequency DESC
LIMIT 10;
